In [2]:
import numpy as np

### EX1: `np.arange`

In [6]:
arr = np.arange(0, 10, 1)
arr # A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### EX2: `np.full`

In [7]:
arr = np.full((3,3), fill_value=True, dtype=bool)
arr #C

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### EX3: Conditional access

In [8]:
arr = np.arange(0,10)
print(arr[arr % 2 == 1]) #A

[1 3 5 7 9]


### EX4: Conditional assign

In [9]:
arr = np.arange(0, 10)
arr[arr % 2 == 1] = -1
print(arr) #B

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### EX5: `np.reshape`

In [10]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d) #D

[[0 1 2 3 4]
 [5 6 7 8 9]]


### EX6 & EX7: `np.repeat` and `np.concat`

In [17]:
arr1 = np.arange(10).reshape(2,-1)
print('arr1',arr1)
arr2 = np.repeat(1, 10).reshape(2,-1)
print('arr2',arr2)
c6= np.concatenate([arr1, arr2], axis=0)  # axis=0 is vertical
c7= np.concatenate([arr1, arr2], axis=1)  # axis=0 is vertical
print("Result of concatenation along axis 0:\n", c6) #A
print("Result of concatenation along axis 1:\n", c7) #C
#A

arr1 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr2 [[1 1 1 1 1]
 [1 1 1 1 1]]
Result of concatenation along axis 0:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Result of concatenation along axis 1:
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Ex8: `np.tile` and `np.repeat`

In [20]:
arr = np.array([1,2,3])
print(np.repeat(arr, 4)) 
print(np.tile(arr, 4)) 
#A

[1 1 1 1 2 2 2 2 3 3 3 3]
[1 2 3 1 2 3 1 2 3 1 2 3]


### EX9: `np.where`

In [21]:

a = np.array([2,6,1,9,10,3,27])
index = np.where((a >= 5) & (a <= 10))
print('result', a[index]) #C

result [ 6  9 10]


### EX10: `np.vectorize`

In [22]:
def max(x,y):
   if x >= y:
      return x
   else:
      return y
   
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(max, otypes=[float]) 
print(pair_max(a, b)) 

[6. 7. 9. 8. 9. 7. 5.]


### EX 11: `np.where`

In [23]:
a = np.array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

print ("Result: ", np.where(a<b , b, a) )

Result:  [6 7 9 8 9 7 5]
